# Generated by Django 2.2.2 on 2019-11-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginpage',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
