# Generated by Django 2.2.2 on 2019-11-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191126_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
